baseurl = "https://www.example.com/"
title = "FerrisEllis.com"
author = "Ferris Ellis"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"


pygmentsstyle       = "trac"
pygmentscodefences  = true

googleAnalytics = "UA-93318303-1"


[params]
  sitename = "FerrisEllis.com"
  twitter_handle = "im_ferris"
  github_handle  = "code-ape"

  dateform = "January 2, 2006"
  description = '''Posts and projects on software, technology, economics, etc.'''

[[menu.main]]
    name = "Posts"
    url  = "/posts"
[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Projects"
    url  = "/projects"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
