baseurl = "https://www.example.com/"
title = "FerrisEllis.com"
author = "Ferris Ellis"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "trac"
pygmentscodefences  = true

[params]
  sitename = "FerrisEllis.com"
  twitter_handle = "im_ferris"
  github_handle  = "code-ape"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Projects"
    url  = "/"
[[menu.main]]
    name = "Resume"
    url  = "/"

