baseURL = "https://ferrisellis.com/"
title = "Ferris Ellis"
canonifyurls = true
languageCode = "en-us"
copyright = "Copyright Ferris Ellis 2017-2019. All rights reserved."
theme = "black-and-light"

pygmentsStyle       = "trac"
#pygmentsUseClasses  = true
pygmentsCodefences  = true

[params]
  sitename = "FerrisEllis.com"
  copyright = "Ferris Ellis"
  twitter_handle = "im_ferris"
  github_handle  = "code-ape"

  dateform = "January 2, 2006"
  description = '''Design, cities, and software.'''

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1

[[menu.main]]
    name = "Newsletter"
    url  = "/newsletter/"
    weight = 2

[[menu.main]]
    name = "Essays"
    url  = "/categories/essays/"
    weight = 3

[[menu.main]]
    name  = "Technical Writings"
    url   = "/categories/technical-writings/"
    weight = 4

[[menu.main]]
    name = "Talks"
    url  = "/categories/talks/"
    weight = 5

[[menu.main]]
    name = "Etc"
    url  = "/categories/etc/"
    weight = 6

[taxonomies]
tag = "tags"
category = "categories"
#series = "series"
