baseurl = "https://ferrisellis.com/"
title = "FerrisEllis.com"
author = "Ferris Ellis"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"


pygmentsStyle       = "trac"
#pygmentsUseClasses  = true
pygmentsCodefences  = true

[params]
  sitename = "FerrisEllis.com"
  twitter_handle = "im_ferris"
  github_handle  = "code-ape"

  dateform = "January 2, 2006"
  description = '''Posts and projects on software, technology, economics, etc.'''
  google_analytics = "UA-93318303-1"

[[menu.main]]
    name = "Posts"
    url  = "/posts"
[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Writings"
    url  = "/writings"
[[menu.main]]
    name = "Talks"
    url  = "/talks"

[taxonomies]
tag = "tags"
#category = "categories"
#series = "series"
